name: CI

on: 
  pull_request:
    branches: [main, development]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      
      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Run linter
        working-directory: frontend
        run: npm run lint

      - name: Run tests
        working-directory: frontend
        run: npm run test